version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance  # This will persist the database
    environment:
      - FLASK_ENV=development
